# Generated by Django 4.2.6 on 2024-08-19 13:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_user_groups_user_user_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article",
                    models.CharField(
                        choices=[
                            ("t_shirt", "t_shirt"),
                            ("sweet_shirt", "sweet_shirt"),
                            ("mug", "mug"),
                            ("key_ring", "key_ring"),
                        ],
                        default="",
                        max_length=255,
                    ),
                ),
                ("description", models.TextField(blank=True, default="", null=True)),
                ("phone", models.CharField(blank=True, max_length=255)),
                ("text", models.TextField(blank=True, max_length=255, null=True)),
                ("design", models.ImageField(blank=True, null=True, upload_to="media")),
                ("color", models.CharField(default="white", max_length=255)),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("S", "S"),
                            ("M", "M"),
                            ("L", "L"),
                            ("XL", "XL"),
                            ("XXL", "XXL"),
                        ],
                        default="",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_seen", models.BooleanField(default=False)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("unseen", "unseen"),
                            ("pending", "pending"),
                            ("progress", "progress"),
                            ("finished", "finished"),
                        ],
                        default="unseen",
                        max_length=255,
                    ),
                ),
                ("is_delivered", models.BooleanField(default=False)),
                ("submitted_date", models.DateTimeField(blank=True, null=True)),
                ("first_url", models.CharField(blank=True, max_length=255)),
                ("last_url", models.CharField(blank=True, max_length=255)),
                ("referrer", models.TextField(blank=True, null=True)),
                ("repetitions", models.PositiveIntegerField(default=0)),
                ("uuid", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Picture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="user-media")),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pictures",
                        to="main.request",
                    ),
                ),
            ],
        ),
    ]
