# Generated by Django 4.2.6 on 2024-08-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_request_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
