# Generated by Django 4.2.6 on 2024-08-21 14:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_statistics_request_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="statistics",
            name="average_request_time",
        ),
        migrations.RemoveField(
            model_name="statistics",
            name="average_size_distribution",
        ),
    ]
